version: '3.2'

services:
    web:
      build: .

      command:    uwsgi  --ini uwsgi.ini
      volumes:
            - .:/usr/src/app

    nginx:
      build: nginx
      depends_on:
      - web
      command: nginx -g 'daemon off;'
      ports:
      - "80:80"
      volumes:
      - ./nginx/static:/var/www/static
      - ./nginx/media:/var/www/media