# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.model_ import Model
from swagger_server.models.dwd_response200_capabilities import Response200Capabilities  # noqa: F401,E501
from swagger_server import util


class Response200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, station_id: str=None, capabilities: List[Response200Capabilities]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param station_id: The station_id of this InlineResponse200.  # noqa: E501
        :type station_id: str
        :param capabilities: The capabilities of this InlineResponse200.  # noqa: E501
        :type capabilities: List[InlineResponse200Capabilities]
        """
        self.swagger_types = {
            'station_id': str,
            'capabilities': List[Response200Capabilities]
        }

        self.attribute_map = {
            'station_id': 'stationId',
            'capabilities': 'capabilities'
        }

        self._station_id = station_id
        self._capabilities = capabilities

    @classmethod
    def from_dict(cls, dikt) -> 'Response200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: Response200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def station_id(self) -> str:
        """Gets the station_id of this InlineResponse200.

        The DWD station id derived from [list](ftp://ftp-cdc.dwd.de/pub/CDC/help/stations_list_soil.txt) or [map](ftp://ftp-cdc.dwd.de/pub/CDC/help/stations_map_soil.png)   # noqa: E501

        :return: The station_id of this InlineResponse200.
        :rtype: str
        """
        return self._station_id

    @station_id.setter
    def station_id(self, station_id: str):
        """Sets the station_id of this InlineResponse200.

        The DWD station id derived from [list](ftp://ftp-cdc.dwd.de/pub/CDC/help/stations_list_soil.txt) or [map](ftp://ftp-cdc.dwd.de/pub/CDC/help/stations_map_soil.png)   # noqa: E501

        :param station_id: The station_id of this InlineResponse200.
        :type station_id: str
        """

        self._station_id = station_id

    @property
    def capabilities(self) -> List[Response200Capabilities]:
        """Gets the capabilities of this InlineResponse200.

        List of available resolutions and their observation types  # noqa: E501

        :return: The capabilities of this InlineResponse200.
        :rtype: List[InlineResponse200Capabilities]
        """
        return self._capabilities

    @capabilities.setter
    def capabilities(self, capabilities: List[Response200Capabilities]):
        """Sets the capabilities of this InlineResponse200.

        List of available resolutions and their observation types  # noqa: E501

        :param capabilities: The capabilities of this InlineResponse200.
        :type capabilities: List[InlineResponse200Capabilities]
        """

        self._capabilities = capabilities
