# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ObservationTypes(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    AIR_TEMPERATURE = "air_temperature"
    CLOUDINESS = "cloudiness"
    CLOUD_TYPE = "cloud_type"
    EXTREME_TEMPERATURE = "extreme_temperature"
    EXTREME_WIND = "extreme_wind"
    KL = "kl"
    MORE_PRECIP = "more_precip"
    PRECIPITATION = "precipitation"
    PRESSURE = "pressure"
    SOIL_TEMPERATURE = "soil_temperature"
    SOLAR = "solar"
    SUN = "sun"
    VISIBILITY = "visibility"
    WATER_EQUIV = "water_equiv"
    WIND = "wind"

    def __init__(self):  # noqa: E501
        """ObservationTypes - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ObservationTypes':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ObservationTypes of this ObservationTypes.  # noqa: E501
        :rtype: ObservationTypes
        """
        return util.deserialize_model(dikt, cls)
