# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Values(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, value: float=None):  # noqa: E501
        """InlineResponse2001Values - a model defined in Swagger

        :param name: The name of this InlineResponse2001Values.  # noqa: E501
        :type name: str
        :param value: The value of this InlineResponse2001Values.  # noqa: E501
        :type value: float
        """
        self.swagger_types = {
            'name': str,
            'value': float
        }

        self.attribute_map = {
            'name': 'name',
            'value': 'value'
        }

        self._name = name
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'Values':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1_values of this InlineResponse2001Values.  # noqa: E501
        :rtype: Values
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this InlineResponse2001Values.

        Name of the parameter, extracted from the headline of the source file.  # noqa: E501

        :return: The name of this InlineResponse2001Values.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this InlineResponse2001Values.

        Name of the parameter, extracted from the headline of the source file.  # noqa: E501

        :param name: The name of this InlineResponse2001Values.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def value(self) -> float:
        """Gets the value of this InlineResponse2001Values.

        Measurement value of the parameter extracted from the source file  # noqa: E501

        :return: The value of this InlineResponse2001Values.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this InlineResponse2001Values.

        Measurement value of the parameter extracted from the source file  # noqa: E501

        :param value: The value of this InlineResponse2001Values.
        :type value: float
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value
